name: "skyops"
version: "1.0.0"
config-version: 2

profile: "skyops"

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]

models:
  skyops:
    staging:
      +materialized: view
      +schema: staging
    intermediate:
      +materialized: view
      +schema: staging
    dimensions:
      +materialized: table
      +schema: analytics
    facts:
      +materialized: table
      +schema: analytics
    marts:
      +materialized: table
      +schema: analytics
