"""Major US hub airports used for weather enrichment (IATA + lat/lon)."""

from __future__ import annotations

# IATA, name, city, state, lat, lon
HUB_AIRPORTS: list[tuple[str, str, str, str, float, float]] = [
    ("ATL", "Hartsfield-Jackson Atlanta", "Atlanta", "GA", 33.6407, -84.4277),
    ("ORD", "O'Hare International", "Chicago", "IL", 41.9742, -87.9073),
    ("DFW", "Dallas/Fort Worth International", "Dallas", "TX", 32.8998, -97.0403),
    ("DEN", "Denver International", "Denver", "CO", 39.8561, -104.6737),
    ("LAX", "Los Angeles International", "Los Angeles", "CA", 33.9416, -118.4085),
    ("JFK", "John F. Kennedy International", "New York", "NY", 40.6413, -73.7781),
    ("SFO", "San Francisco International", "San Francisco", "CA", 37.6213, -122.3790),
    ("SEA", "Seattle-Tacoma International", "Seattle", "WA", 47.4502, -122.3088),
    ("LAS", "Harry Reid International", "Las Vegas", "NV", 36.0840, -115.1537),
    ("MCO", "Orlando International", "Orlando", "FL", 28.4312, -81.3081),
    ("CLT", "Charlotte Douglas International", "Charlotte", "NC", 35.2144, -80.9473),
    ("PHX", "Phoenix Sky Harbor", "Phoenix", "AZ", 33.4352, -112.0101),
    ("MIA", "Miami International", "Miami", "FL", 25.7959, -80.2870),
    ("IAH", "George Bush Intercontinental", "Houston", "TX", 29.9902, -95.3368),
    ("EWR", "Newark Liberty International", "Newark", "NJ", 40.6895, -74.1745),
    ("BOS", "Logan International", "Boston", "MA", 42.3656, -71.0096),
    ("MSP", "Minneapolis–Saint Paul", "Minneapolis", "MN", 44.8848, -93.2223),
    ("DTW", "Detroit Metropolitan", "Detroit", "MI", 42.2162, -83.3554),
    ("PHL", "Philadelphia International", "Philadelphia", "PA", 39.8744, -75.2424),
    ("LGA", "LaGuardia", "New York", "NY", 40.7769, -73.8740),
    ("BWI", "Baltimore/Washington International", "Baltimore", "MD", 39.1754, -76.6683),
    ("SLC", "Salt Lake City International", "Salt Lake City", "UT", 40.7899, -111.9791),
    ("SAN", "San Diego International", "San Diego", "CA", 32.7338, -117.1933),
    ("TPA", "Tampa International", "Tampa", "FL", 27.9755, -82.5332),
    ("DCA", "Ronald Reagan Washington National", "Washington", "DC", 38.8512, -77.0402),
    ("MDW", "Chicago Midway", "Chicago", "IL", 41.7868, -87.7522),
    ("HNL", "Daniel K. Inouye International", "Honolulu", "HI", 21.3187, -157.9225),
    ("PDX", "Portland International", "Portland", "OR", 45.5898, -122.5951),
    ("STL", "St. Louis Lambert", "St. Louis", "MO", 38.7499, -90.3748),
    ("AUS", "Austin-Bergstrom", "Austin", "TX", 30.1945, -97.6699),
]

KEEP_COLUMNS = [
    "FlightDate",
    "Year",
    "Month",
    "Reporting_Airline",
    "Flight_Number_Reporting_Airline",
    "Origin",
    "Dest",
    "CRSDepTime",
    "DepTime",
    "DepDelay",
    "TaxiOut",
    "TaxiIn",
    "CRSArrTime",
    "ArrTime",
    "ArrDelay",
    "Cancelled",
    "Diverted",
    "CRSElapsedTime",
    "ActualElapsedTime",
    "AirTime",
    "Distance",
    "CarrierDelay",
    "WeatherDelay",
    "NASDelay",
    "SecurityDelay",
    "LateAircraftDelay",
]

# BTS column name variants across PREZIP vintages
COLUMN_ALIASES = {
    "FlightDate": ["FlightDate", "FL_DATE"],
    "Year": ["Year", "YEAR"],
    "Month": ["Month", "MONTH"],
    "Reporting_Airline": ["Reporting_Airline", "OP_UNIQUE_CARRIER", "UniqueCarrier"],
    "Flight_Number_Reporting_Airline": [
        "Flight_Number_Reporting_Airline",
        "OP_CARRIER_FL_NUM",
        "FlightNum",
    ],
    "Origin": ["Origin", "ORIGIN"],
    "Dest": ["Dest", "DEST"],
    "CRSDepTime": ["CRSDepTime", "CRS_DEP_TIME"],
    "DepTime": ["DepTime", "DEP_TIME"],
    "DepDelay": ["DepDelay", "DEP_DELAY"],
    "TaxiOut": ["TaxiOut", "TAXI_OUT"],
    "TaxiIn": ["TaxiIn", "TAXI_IN"],
    "CRSArrTime": ["CRSArrTime", "CRS_ARR_TIME"],
    "ArrTime": ["ArrTime", "ARR_TIME"],
    "ArrDelay": ["ArrDelay", "ARR_DELAY"],
    "Cancelled": ["Cancelled", "CANCELLED"],
    "Diverted": ["Diverted", "DIVERTED"],
    "CRSElapsedTime": ["CRSElapsedTime", "CRS_ELAPSED_TIME"],
    "ActualElapsedTime": ["ActualElapsedTime", "ACTUAL_ELAPSED_TIME"],
    "AirTime": ["AirTime", "AIR_TIME"],
    "Distance": ["Distance", "DISTANCE"],
    "CarrierDelay": ["CarrierDelay", "CARRIER_DELAY"],
    "WeatherDelay": ["WeatherDelay", "WEATHER_DELAY"],
    "NASDelay": ["NASDelay", "NAS_DELAY"],
    "SecurityDelay": ["SecurityDelay", "SECURITY_DELAY"],
    "LateAircraftDelay": ["LateAircraftDelay", "LATE_AIRCRAFT_DELAY"],
}
