select
    fl_date,
    year,
    month,
    op_unique_carrier as carrier_code,
    op_carrier_fl_num as flight_number,
    origin as origin_airport,
    dest as dest_airport,
    dep_delay,
    arr_delay,
    cancelled,
    diverted,
    distance,
    is_on_time,
    carrier_delay,
    weather_delay,
    nas_delay,
    security_delay,
    late_aircraft_delay,
    origin_temp_max_c,
    origin_precip_mm,
    origin_wind_max_kmh,
    origin_weather_bucket
from {{ ref('int_flights_enriched') }}
