version: 2

models:
  - name: stg_flights
    columns:
      - name: fl_date
        tests: [not_null]
      - name: origin
        tests: [not_null]
      - name: dest
        tests: [not_null]
      - name: op_unique_carrier
        tests: [not_null]
  - name: stg_weather_daily
    columns:
      - name: airport_iata
        tests: [not_null]
      - name: weather_date
        tests: [not_null]
  - name: stg_airports
    columns:
      - name: iata_code
        tests: [unique, not_null]
  - name: stg_ingestion_runs
    columns:
      - name: source_name
        tests: [not_null]
      - name: status
        tests:
          - not_null
          - accepted_values:
              values: ['ok', 'error']
      - name: row_count
        tests: [not_null]
